// Seed data for the design hub
const SEED_PROJECTS = [
  {
    id: "p-onboarding-v3",
    title: "Onboarding v3",
    desc: "Redesigning the first-run experience to lift D7 retention. New step-by-step with progressive disclosure.",
    status: "ongoing",
    priority: 3,
    tags: ["mobile", "growth", "core"],
    cover: { kind: "stripes", c1: "oklch(0.78 0.10 38)", c2: "oklch(0.92 0.04 38)", angle: "55deg" },
    coverLabel: "ONBOARDING",
    pinned: true,
    figma: [
      { name: "Onboarding — flows", url: "figma.com/file/abc123/onboarding-flows" },
      { name: "Onboarding — components", url: "figma.com/file/def456/onboarding-comp" },
    ],
    proto: [
      { name: "Webapp prototype", url: "proto.acme.com/onb-v3", kind: "web" },
      { name: "Figma prototype", url: "figma.com/proto/abc123", kind: "figma" },
    ],
    docs: [
      { name: "PRD — Onboarding v3", url: "docs.google.com/document/d/1a2b" },
      { name: "Research synthesis", url: "docs.google.com/document/d/3c4d" },
    ],
    stakeholders: ["Mia (PM)", "Sam (Eng lead)"],
    updated: "2 days ago",
    started: "Mar 4, 2026",
    notes: "Mia wants to ship by EOQ. Need to validate step 2 with research next week.",
    history: [
      { date: "May 11", text: "Shared v3 prototype with Mia" },
      { date: "May 6", text: "Updated component spec after eng review" },
      { date: "Apr 28", text: "Kickoff with PM + Eng" },
    ],
  },
  {
    id: "p-billing-redesign",
    title: "Billing redesign",
    desc: "Untangle the upgrade modal mess. Consolidate three legacy flows into one clear path.",
    status: "ongoing",
    priority: 2,
    tags: ["web", "monetization"],
    cover: { kind: "grid", c2: "oklch(0.75 0.08 230 / 0.4)", c3: "oklch(0.96 0.02 230)" },
    coverLabel: "BILLING",
    figma: [{ name: "Billing — main", url: "figma.com/file/bil999/billing" }],
    proto: [{ name: "Figma click-thru", url: "figma.com/proto/bil999", kind: "figma" }],
    docs: [{ name: "Pricing v2 doc", url: "docs.google.com/document/d/bill" }],
    stakeholders: ["Jordan (PM)", "Priya (Growth)"],
    updated: "Yesterday",
    started: "Apr 12, 2026",
    notes: "Waiting on legal review of plan names.",
    history: [
      { date: "May 12", text: "Iterated on plan card layout" },
      { date: "May 4", text: "First round of Figma exploration" },
    ],
  },
  {
    id: "p-mobile-nav",
    title: "Mobile bottom nav",
    desc: "Compact 4-tab nav replacing the current hamburger. Hi-fi spec + handoff.",
    status: "shipped",
    priority: 2,
    tags: ["mobile", "core"],
    cover: { kind: "blob", c1: "oklch(0.85 0.08 155)", c2: "oklch(0.88 0.04 80)", c3: "oklch(0.96 0.01 155)" },
    coverLabel: "MOBILE NAV",
    figma: [{ name: "Mobile nav — final", url: "figma.com/file/nav777/mobile-nav" }],
    proto: [{ name: "Webapp prototype", url: "proto.acme.com/nav", kind: "web" }],
    docs: [{ name: "Handoff spec", url: "docs.google.com/document/d/nav" }],
    stakeholders: ["Ben (Eng)", "Mia (PM)"],
    updated: "3 weeks ago",
    started: "Feb 3, 2026",
    shipped: "Apr 22, 2026",
    notes: "Shipped clean. Watch session length metric next quarter.",
    history: [
      { date: "Apr 22", text: "Shipped to production" },
      { date: "Apr 14", text: "Final handoff to Eng" },
      { date: "Mar 30", text: "User testing — passed all tasks" },
    ],
  },
  {
    id: "p-empty-states",
    title: "Empty states audit",
    desc: "Quick illustration pass across 24 empty states. Consistent voice + visual system.",
    status: "ongoing",
    priority: 1,
    tags: ["adhoc", "polish"],
    cover: { kind: "type", c1: "oklch(0.45 0.14 280)", c3: "oklch(0.94 0.04 280)", text: "Aa" },
    figma: [{ name: "Empty states — library", url: "figma.com/file/empty/empty-states" }],
    proto: [],
    docs: [{ name: "Voice guidelines", url: "docs.google.com/document/d/voice" }],
    stakeholders: ["Self"],
    updated: "4 days ago",
    started: "May 1, 2026",
    notes: "20/24 done. Holding the last 4 until copywriter weighs in.",
    history: [
      { date: "May 9", text: "Reviewed 12 states with copywriter" },
      { date: "May 2", text: "Audit started" },
    ],
  },
  {
    id: "p-design-tokens",
    title: "Design tokens v2",
    desc: "Migrate from one-off hex values to semantic token names. Light + dark.",
    status: "ongoing",
    priority: 3,
    tags: ["system", "core"],
    cover: { kind: "stripes", c1: "oklch(0.50 0.02 60)", c2: "oklch(0.92 0.01 60)", angle: "0deg" },
    coverLabel: "TOKENS",
    pinned: true,
    figma: [
      { name: "Tokens — source of truth", url: "figma.com/file/tok/tokens" },
      { name: "Dark mode exploration", url: "figma.com/file/tok-dark" },
    ],
    proto: [{ name: "Token preview app", url: "tokens.acme.com", kind: "web" }],
    docs: [
      { name: "Token naming RFC", url: "docs.google.com/document/d/rfc-tok" },
      { name: "Migration plan", url: "docs.google.com/spreadsheets/d/tok-mig" },
    ],
    stakeholders: ["Lin (Eng)", "Self"],
    updated: "Today",
    started: "Jan 14, 2026",
    notes: "Eng wants this done before the iOS refactor. Pressure on.",
    history: [
      { date: "May 13", text: "Updated dark-mode tokens" },
      { date: "May 1", text: "Reviewed RFC with Lin" },
    ],
  },
  {
    id: "p-search-redesign",
    title: "Search redesign",
    desc: "Universal search with command-bar pattern. Filters, recents, AI suggestions.",
    status: "hold",
    priority: 2,
    tags: ["web", "ai"],
    cover: { kind: "grid", c2: "oklch(0.78 0.10 80 / 0.5)", c3: "oklch(0.96 0.04 80)" },
    coverLabel: "SEARCH",
    figma: [{ name: "Search — explorations", url: "figma.com/file/srch/search" }],
    proto: [{ name: "Figma proto", url: "figma.com/proto/srch", kind: "figma" }],
    docs: [{ name: "AI suggestion spec", url: "docs.google.com/document/d/srch-ai" }],
    stakeholders: ["Jordan (PM)"],
    updated: "1 month ago",
    started: "Mar 18, 2026",
    notes: "Paused — waiting on AI infra team. Pick back up in June.",
    history: [
      { date: "Apr 8", text: "Paused — waiting on AI team" },
      { date: "Apr 1", text: "Reviewed v2 with Jordan" },
    ],
  },
  {
    id: "p-marketing-site",
    title: "Marketing site refresh",
    desc: "Landing + pricing + about. Editorial-style typography refresh.",
    status: "shipped",
    priority: 2,
    tags: ["web", "brand"],
    cover: { kind: "blob", c1: "oklch(0.85 0.10 38)", c2: "oklch(0.85 0.08 80)", c3: "oklch(0.97 0.02 38)" },
    coverLabel: "MARKETING",
    figma: [{ name: "Marketing — final", url: "figma.com/file/mkt/marketing" }],
    proto: [{ name: "Webapp prototype", url: "preview.acme.com", kind: "web" }],
    docs: [{ name: "Copy doc", url: "docs.google.com/document/d/mkt-copy" }],
    stakeholders: ["Eva (Marketing)", "Self"],
    updated: "5 weeks ago",
    started: "Jan 8, 2026",
    shipped: "Apr 1, 2026",
    notes: "Shipped! Eva loved the editorial direction.",
    history: [
      { date: "Apr 1", text: "Site went live" },
      { date: "Mar 22", text: "Final review w/ Eva" },
    ],
  },
  {
    id: "p-icon-tweak",
    title: "Icon set tweaks",
    desc: "Stroke-weight pass on 14 nav icons after pixel-snapping complaints.",
    status: "ongoing",
    priority: 1,
    tags: ["adhoc", "polish"],
    cover: { kind: "type", c1: "oklch(0.45 0.12 155)", c3: "oklch(0.94 0.04 155)", text: "★" },
    figma: [{ name: "Icon library", url: "figma.com/file/icons/icons" }],
    proto: [],
    docs: [],
    stakeholders: ["Lin (Eng)"],
    updated: "Today",
    started: "May 10, 2026",
    notes: "Quick one. Aim for EOW.",
    history: [
      { date: "May 13", text: "First pass on 8/14 icons" },
    ],
  },
  {
    id: "p-dashboard-v2",
    title: "Analytics dashboard v2",
    desc: "Charts library + customizable layout. Tight constraints from the data team.",
    status: "ongoing",
    priority: 3,
    tags: ["web", "data"],
    cover: { kind: "grid", c2: "oklch(0.78 0.10 280 / 0.5)", c3: "oklch(0.96 0.03 280)" },
    coverLabel: "DASHBOARD",
    figma: [
      { name: "Dashboard — main", url: "figma.com/file/dash/dashboard" },
      { name: "Chart components", url: "figma.com/file/dash-chart" },
    ],
    proto: [{ name: "Webapp prototype", url: "proto.acme.com/dash", kind: "web" }],
    docs: [{ name: "PRD — Dashboard v2", url: "docs.google.com/document/d/dash" }],
    stakeholders: ["Priya (Growth)", "Tom (Data)"],
    updated: "1 week ago",
    started: "Mar 25, 2026",
    notes: "Tom is pushing back on the chart density. Need a compromise.",
    history: [
      { date: "May 6", text: "Iterated on chart density" },
      { date: "Apr 18", text: "Kickoff" },
    ],
  },
  {
    id: "p-error-system",
    title: "Error message system",
    desc: "Standard error templates: tone, structure, recovery actions.",
    status: "archived",
    priority: 1,
    tags: ["system", "polish"],
    cover: { kind: "stripes", c1: "oklch(0.60 0.02 60)", c2: "oklch(0.85 0.01 60)", angle: "90deg" },
    coverLabel: "ERRORS",
    figma: [{ name: "Errors — old", url: "figma.com/file/err/errors" }],
    proto: [],
    docs: [{ name: "Error voice doc", url: "docs.google.com/document/d/err-voice" }],
    stakeholders: ["Self"],
    updated: "6 months ago",
    started: "Oct 20, 2025",
    notes: "Superseded by the broader voice guidelines work.",
    history: [{ date: "Dec 2", text: "Archived" }],
  },
  {
    id: "p-old-onboarding",
    title: "Onboarding v2",
    desc: "Previous redesign. Kept around for reference and metrics comparison.",
    status: "archived",
    priority: 2,
    tags: ["mobile", "growth"],
    cover: { kind: "stripes", c1: "oklch(0.70 0.04 280)", c2: "oklch(0.90 0.02 280)", angle: "55deg" },
    coverLabel: "ONB v2",
    figma: [{ name: "Onboarding v2", url: "figma.com/file/onb2/onb-v2" }],
    proto: [{ name: "Old proto", url: "proto.acme.com/onb-v2", kind: "web" }],
    docs: [],
    stakeholders: ["Mia (PM)"],
    updated: "1 year ago",
    started: "May 12, 2025",
    shipped: "Jul 30, 2025",
    notes: "Lessons learned: step 2 was a graveyard.",
    history: [{ date: "Jul 30 2025", text: "Shipped" }],
  },
  {
    id: "p-pm-deck",
    title: "Q2 design review deck",
    desc: "One-off slide deck for the Q2 design review. Stakeholder presentation.",
    status: "shipped",
    priority: 1,
    tags: ["adhoc", "presentation"],
    cover: { kind: "type", c1: "oklch(0.45 0.14 38)", c3: "oklch(0.94 0.04 38)", text: "Q2" },
    figma: [{ name: "Deck — figma source", url: "figma.com/file/q2/q2-deck" }],
    proto: [],
    docs: [{ name: "Slides — Q2 review", url: "docs.google.com/presentation/d/q2" }],
    stakeholders: ["Leadership"],
    updated: "2 weeks ago",
    started: "Apr 25, 2026",
    shipped: "May 1, 2026",
    notes: "Went well. Saved as template for Q3.",
    history: [{ date: "May 1", text: "Presented" }],
  },
];

const ALL_TAGS = ["mobile", "web", "core", "growth", "monetization", "system", "polish", "ai", "data", "brand", "adhoc", "presentation"];
